### ISSUE TITLE
How to configure ORM Mapping?

### ISSUE THREAD

**Issue by lowtower** [DASPRiD/container-interop-doctrine#10]
How to configure ORM Mapping?

I have configured doctrine in zend expressive following [xtreamwayz' guide](https://xtreamwayz.com/blog/2015-12-12-setup-doctrine-for-zend-expressive):

``` php
// ORM mapping by Annotation
AnnotationRegistry::registerFile('vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php');
$driver = new AnnotationDriver(
    new AnnotationReader(),
    ['src/Domain']
);
```

How would I configure ORM mapping with container-interop-doctrine?
Thanks in advance,
LT.

**Comment by mattgrosse** [comment]
This guide will help you: https://www.jamestitcumb.com/posts/integrating-doctrine-expressive-easier

But all you really need to do is install container-interop-doctrine via composer, then make a config/autoload/doctrine.local.php file. [This file](https://github.com/DASPRiD/container-interop-doctrine/blob/master/example/minimal-config.php) is the minimal config example. You can copy that and put your db connection info in there, change the XmlDriver::class to AnnotationDriver::class, and update the path to point to the correct location (which looks like src/Domain from your example).
