### ISSUE TITLE
Question: how to handle custom doctrine types?

### ISSUE THREAD

**Issue by lowtower** [DASPRiD/container-interop-doctrine#20]
Hello,

how would one add custom doctrine types, such as Ramsey's UUid https://github.com/ramsey/uuid-doctrine
I found 'doctrine_mapping_types' => [], in the full config, but this seems to only **alter existing** type mappings but not add new types.

Cheers,
LowTower.

**Comment by DASPRiD** [comment]
Nope, that section is specifically for adding custom types.

**Comment by DASPRiD** [comment]
Actually, nevermind. Scroll down to the end of the full config example, there's a `types` array.

**Comment by lowtower** [comment]
Got it,
thanks a lot!
Cheers,
LT.
