### ISSUE TITLE
Idea - Migrations factory

### ISSUE THREAD

**Issue by asgrim** [DASPRiD/container-interop-doctrine#28]
Got asked after my talk about whether we support Doctrine Migrations, which I realise we implemented manually on other projects with a factory.

This is a placeholder to remind me to add that factory (optionally, of course) into here so others can benefit :+1:

**Comment by luckals** [comment]
What do you think about my PR #31  for fixing this issue?

**Comment by asgrim** [comment]
This repository is now deprecated. If you are still experiencing this issue, please feel free to open a new issue at https://github.com/Roave/psr-container-doctrine/issues - thanks!
