### ISSUE TITLE
Idea: ZF integration

### ISSUE THREAD

**Issue by asgrim** [DASPRiD/container-interop-doctrine#29]
Placeholder - @adamculp will fill in details, possibly some ConfigProvider stuff?

**Comment by azjezz** [comment]
it would be better to have an `Integration` namespace containing ZF ConfigProvider alongside a ServiceProvider for silex, laravel and lumen.

maybe other frameworks too ?

**Comment by asgrim** [comment]
This repository is now deprecated. If you are still experiencing this issue, please feel free to open a new issue at https://github.com/Roave/psr-container-doctrine/issues - thanks!
