### ISSUE TITLE
[PHP 7.3] [Doctrine]  Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by guillaumemaka** [DASPRiD/container-interop-doctrine#39]
Recently updated to PHP 7.3 I got this warning:

Using project autoloader based on current working directory
PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /code/ebos/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2718

See doctrine/doctrine2#7402
Fixed doctrine/doctrine2#7325

Do you plan to update the dependencies ?

**Comment by icetee** [comment]
Did not jump to the main version, will automatically download the latest version `v2.7.0`.

**Comment by asgrim** [comment]
This repository is now deprecated. If you are still experiencing this issue, please feel free to open a new issue at https://github.com/Roave/psr-container-doctrine/issues - thanks!
