### ISSUE TITLE
Could you provide an example using AnnotationDriver ?

### ISSUE THREAD

**Issue by ricardofiorani** [DASPRiD/container-interop-doctrine#4]
I having some kind of difficulties to have it run the simplest way possible straight out of ["Getting Started with Doctrine"](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/getting-started.html) tutorial.

I'm getting a "Cannot instantiate abstract class Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver" error.

I'm using it with ZF-Expressive (ZendServiceManager) and my config is as follows

``` php
return [
    'dependencies' => [
        'factories' => [
            \Doctrine\ORM\EntityManager::class => \ContainerInteropDoctrine\EntityManagerFactory::class,
        ],
    ],
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'params' => [
                    'url' => 'mysql://root@localhost/database',
                ],
            ],
        ],
        'driver' => [
            'orm_default' => [
                'class' => \Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver::class,
                'paths' => [
                    __DIR__.'/../../module/application/src/Entity',
                    __DIR__.'/../../module/admin/src/Entity',
                ],
            ],
        ],
    ],
```

**Comment by DASPRiD** [comment]
According to the following post, it's `\Doctrine\ORM\Mapping\Driver\AnnotationDriver::class`:
http://www.jamestitcumb.com/posts/integrating-doctrine-expressive-easier

**Comment by ricardofiorani** [comment]
Thank you !!
