### ISSUE TITLE
Doctrine CLI error

### ISSUE THREAD

**Issue by GoDoY-SP-** [DASPRiD/container-interop-doctrine#8]
Hi,
## How can I fix this error?

`
$ ./vendor/bin/doctrine

Fatal error: Uncaught Doctrine\Common\Proxy\Exception\OutOfBoundsException: Missing "class" config key in \expressive-test\vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 754

Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "doctrine.entity_manager.orm_default" could not be created. Reason: Missing "class" config key in \expressive-test\vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 754

Call Stack:
    0.0008     347912   1. {main}() \expressive-test\vendor\doctrine\orm\bin\doctrine:0
    0.0015     354960   2. include('\expressive-test\vendor\doctrine\orm\bin\doctrine.php') \expressive-test\vendor\doctrine\orm\bin\doctrine:4
    0.0580     673304   3. require('\expressive-test\cli-config.php') \expressive-test\vendor\doctrine\orm\bin\doctrine.php:55
    0.0794     971616   4. Zend\ServiceManager\ServiceManager->get() \expressive-test\cli-config.php:24
    0.0794     971616   5. Zend\ServiceManager\ServiceManager->doCreate() \expressive-test\vendor\zendframework\zend-servicemanager\src\ServiceManager.php:195

PHP Fatal error:  Uncaught Doctrine\Common\Proxy\Exception\OutOfBoundsException: Missing "class" config key in \expressive-test\vendor\dasprid\container-interop-doctrine\src\DriverFactory.php:41
`

**Comment by DASPRiD** [comment]
By adding a `class` config key. Your container must return an array or array object under the name `config`.

**Comment by manuakasam** [comment]
For future references when people are as ridiculously stupid as I am.

Check the name of your config file. Don't forget to add the `.local.` or `.global.` part, otherwise the configuration will never be loaded and you'll keep throwing your head against the wall to find this.

Don't waste as much time on a silly mistake as I just did ;)
