### ISSUE TITLE
Make use of sandrokeil/interop-config

### ISSUE THREAD

**Issue by prolic** [DASPRiD/container-interop-doctrine#9]
this would simplify factory code a lot

/cc @sandrokeil

**Comment by sandrokeil** [comment]
@DASPRiD If you interested in [interop-config](https://github.com/sandrokeil/interop-config), I can bring a PR.

**Comment by DASPRiD** [comment]
Generally I like simplifying things, but I'm not a huge fan of how interop-config does it, architecture-wise. There is not really a good reason to have that functionality injected via a trait instead of a normal class dependency.

**Comment by sandrokeil** [comment]
I had an abstract class in prior versions. My decision was to use a trait to increase flexibility e.g. allow other base classes. What's the benefit of having an abstract class which contains the functions of the trait?

**Comment by DASPRiD** [comment]
As I said rather use a dependency. An abstract class is just as bad.
